language: csharp
mono: none
dotnet: 2.1.502
script:
- dotnet build -c Release
- dotnet test
before_deploy:
- dotnet pack -c Release -p:Version=$TRAVIS_TAG
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push /home/travis/build/rsocket/rsocket-net/RSocket.Core/bin/Release/RSocket.Core.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
  on:
    tags: true
