name: Release Java CI

on:
  # Trigger the workflow on push
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching *, i.e. 1.0, 20.15.10

jobs:
    publish:

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ windows-latest ]
            fail-fast: false

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 2.1.809

            - name: Setup Nuget
              uses: nuget/setup-nuget@v1
              with:
                    nuget-api-key: ${{ secrets.nugetApiKey }}
                    nuget-version: '5.x'
            - name: Install dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --configuration Release --no-restore
            - name: Test
              run: dotnet test --no-restore --verbosity normal
            - name: Package
              run: dotnet pack -c Release -p:Version=${releaseVersion}
              env:
                  releaseVersion: ${{ github.ref }}
            - name: Restore Cert File
              run: echo ${codeSigningCer} > code_signing.cer
              env:
                  codeSigningCer: ${{ CODE_SIGN_CER }}
            - name: Sign Package
              run: nuget sign rsocket-net/RSocket.Core/bin/Release/RSocket.Core.*.nupkg -CertificatePath code_signing.cer
            - name: Remove Cert File
              run: rm -rf code_signing.cer
            - name: publish
              run: dotnet nuget push rsocket-net/RSocket.Core/bin/Release/RSocket.Core.*.nupkg --api-key ${nugetApiKey} --source https://api.nuget.org/v3/index.json
              env:
                  nugetApiKey: ${{ secrets.nugetApiKey }}
