name: Release Java CI

on:
    # Trigger the workflow on push
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - '*' # Push events to matching *, i.e. 1.0, 20.15.10

jobs:
    publish:

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ windows-latest ]
            fail-fast: false

        steps:
            -   uses: actions/checkout@v2
            -   name: Setup .NET Core
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 2.1.809
            -   name: Set .NET Version
                run: dotnet new globaljson --sdk-version 2.1.809
            -   name: Setup Nuget
                uses: nuget/setup-nuget@v1
                with:
                    nuget-api-key: ${{ secrets.nugetApiKey }}
                    nuget-version: '5.x'
            -   name: Install dependencies
                run: dotnet restore
            -   name: Build
                run: dotnet build --configuration Release --no-restore
            -   name: Test
                run: dotnet test --no-restore --verbosity normal
            -   name: Package
                run: |
                    $releaseVersion = "${{ github.ref }}".Split("/")["${{ github.ref }}".Split("/").Length - 1]
                    dotnet pack -c Release -p:Version=${releaseVersion}
            -   name: Restore Cert File
                run: |
                    New-Item "code_signing.b64" -ItemType File -Value "${{ secrets.CODE_SIGN_CER }}"
                    certutil -decode code_signing.b64 code_signing.cer
                    del code_signing.b64
            -   name: Sign Package
                run: nuget sign D:\a\rsocket-net\rsocket-net\RSocket.Core\bin\Release\RSocket.Core.*.nupkg -CertificatePath code_signing.cer -Timestamper http://time.certum.pl
            -   name: Remove Cert File
                if: ${{ always() }}
                run: del code_signing.cer
            -   name: publish
                run: dotnet nuget push D:\a\rsocket-net\rsocket-net\RSocket.Core\RSocket.Core\bin\Release\RSocket.Core.*.nupkg --api-key ${{ secrets.nugetApiKey }} --source https://api.nuget.org/v3/index.json
